- name: Configure test firewall
  hosts: firewall

  tasks:
    - name: Ensure nftables is installed
      ansible.builtin.apt:
        name: nftables
        state: present
    
    - name: Check if filter table exists
      ansible.builtin.command: nft list table inet filter
      register: filter_table
      changed_when: false
      failed_when: false
    
    - name: Create filter table
      ansible.builtin.command: nft add table inet filter
      when: filter_table.rc != 0